### ISSUE TITLE
Can't get getAccessToken working

### ISSUE THREAD

**Issue by ericvrp** [lukasolson/fitbit-node#15]
I have received authorization through getAuthorizateUrl but after getAccessToken I get this error on the console. Where should I start looking for a solution?

> XMLHttpRequest cannot load https://api.fitbit.com/oauth2/token. Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. Origin 'http://localhost:3000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

**Comment by ericvrp** [comment]
P.S. this is a react app running on port 3000 with an nginx proxy_pass to it.

**Comment by mbmccormick** [comment]
Hi @ericvrp! I'm not familiar with react. Can you capture and share the web requests from your local machine to see what the raw HTTP response is from the Fitbit API? This will help with debugging.

**Comment by ericvrp** [comment]
I the meantime I switched to requesting the token from the server side.
