### ISSUE TITLE
Fitbit API 1.0 is too old (for example no sleep stages)

### ISSUE THREAD

**Issue by haraldronge** [lukasolson/fitbit-node#17]
Would you please change the Fitbit API version called to 1.2 in fitbit-api-client.js on line 181 like so:

function getUrl(path, userId) {
    return path = 'https://api.fitbit.com/1.2/user/' + (userId || '-') + path;
}

Fully backward compatible (except 409 error-codes maybe?). Otherwise this keeps coming up :-). Or better still: an optional version-parameter?

Thank you, Harald

**Comment by jmdiego** [comment]
This has been addressed in the 2.1.0 release
