### ISSUE TITLE
refreshAccessToken does nothing

### ISSUE THREAD

**Issue by handsingroup** [lukasolson/fitbit-node#18]
When I attempt to print results from the promise, or even just print a "Hello," there's nothing. I'm passing in the access token and refresh token as strings, and the expiration in seconds as an integer. There are no errors being reported during runtime. Oddly enough, getAccessToken works perfectly fine.

**Comment by Deamoner** [comment]
Yea I am getting the same behavior. Anything to be done? Can I do a manual get or something?

**Comment by Deamoner** [comment]
I looked further into this. It appears that the the resolve recommendation is not sending back anything. Perhaps this is an issue with old Q library.

**Comment by jmdiego** [comment]
This behavior has been fixed in the 2.1.0 release
