### ISSUE TITLE
allow non-user dependent requests

### ISSUE THREAD

**Issue by xxzefgh** [lukasolson/fitbit-node#26]
What do you think about this change?
https://github.com/sarkestudio/fitbit-node/blob/master/fitbit-api-client.js#L26-L31
I can make a PR if it makes sense.

**Comment by nurseybushc** [comment]
When would you not pass userId?

**Comment by xxzefgh** [comment]
food api has several endpoints where you don't need user
![screenshot_20180301-220422](https://user-images.githubusercontent.com/6980903/36861171-992f980a-1d9c-11e8-8b3c-8dd99290f594.png)

**Comment by jmdiego** [comment]
What about, instead of requiring userId as false, or setting it as default, just check if it's falsy and do:

```
getUrl(path, userId){
    return `https://api.fitbit.com/${this.apiVersion}${userId ? `/user/${userId}` : ''}${path}`;
}
```

**Comment by xxzefgh** [comment]
@jmdiego That would be a breaking change, current implementation automatically inserts `-` if you don't pass userId, which is useful

**Comment by jmdiego** [comment]
@thisdotvoid you are right, what about:

```
getUrl(path, userId){
    let userSubPath = userId === false ? '' : `/user/${userId || '-'}`;
    return `https://api.fitbit.com/${this.apiVersion}${userSubPath}${path}`;
}
```

Your initial proposal also removed the empty user possibility, so, I guess this would be the most comprehensive solution to handle all three use cases.

**Comment by xxzefgh** [comment]
@jmdiego hmm you are right 🤔 made a pr
