### ISSUE TITLE
Add OAuth2 support

### ISSUE THREAD

**Issue by pplewa** [lukasolson/fitbit-node#3]
Fitbit is phasing OAuth 1, https://dev.fitbit.com/docs/oauth2/

**Comment by ryanbuiltthat** [comment]
Is this repo still active?

**Comment by lukasolson** [comment]
@ryanbuiltthat Yes, thanks to @mbmccormick.

**Comment by lukasolson** [comment]
Closed by https://github.com/lukasolson/fitbit-node/pull/4.
