### ISSUE TITLE
Is redirectURL is mandatory for getAccessToken(code, redirectUrl) function ? 

### ISSUE THREAD

**Issue by gbharath5182** [lukasolson/fitbit-node#30]
Is redirectURL is mandatory for getAccessToken(code, redirectUrl) function ? because we are doing Authorize from Mobile APP and getting tokens in backend (NODE JS).

**Comment by nurseybushc** [comment]
redirectURL would be the backend endpoint address where you want to capture the tokens

**Comment by nurseybushc** [comment]
Marking as closed
