### ISSUE TITLE
Push version to NPM?

### ISSUE THREAD

**Issue by abeaclark** [lukasolson/fitbit-node#5]
Hello, 

Thanks for making this package. It took me a little while to figure out how to use it because NPM seems to have a pretty different version than what is represented here. 

Have you considered pushing this version to NPM? I'm pulling directly from this repo now, so it is working.

I am new to coding / node.js so forgive me if this is niave. 

Thanks, 

Abe

**Comment by lukasolson** [comment]
Not naive at all. I just published the new version. Thanks for bringing this up.
