### ISSUE TITLE
How about revoking the access to the application?

### ISSUE THREAD

**Issue by ShrujanKotturi** [lukasolson/fitbit-node#9]
Whenever the user wants to revoke the access, how do we do that?
I see the revoke access is a POST operation with body parameter.

**Comment by mbmccormick** [comment]
What is the scenario that you are trying to enable?

From what I can tell, the Fitbit API does not support revoking an application's permissions from within that application. The user can only do this from the Fitbit website and your application does not receive any notification of this event. Instead, any API calls your application makes on behalf of that user after they have revoked your application's permission to their account will fail with a 403 Forbidden response.

**Comment by ShrujanKotturi** [comment]
According to my use-case, it's the user who revokes the access to the application.
Is there any way i could implement this?

**Comment by mbmccormick** [comment]
I stand corrected, the Fitbit API does [support](https://dev.fitbit.com/docs/oauth2/#revoking-access-tokens) this! `fitbit-node` does not support this today, but it is technically possible. Pull requests welcome! 😉

**Comment by twelve17** [comment]
Hey @mbmccormick, I've submitted a PR for this.  Let me know what you think.  Thanks!

**Comment by mbmccormick** [comment]
This is now available in version 2.0.3 of `fitbit-node`, thanks to @twelve17!
